# Generated by Django 5.0.6 on 2026-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='message_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
