# Generated by Django 5.0.6 on 2026-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0002_account_message_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
