# Generated by Django 5.0.6 on 2026-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureapp', '0003_account_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
